statsd: Don't use <nixpkgs>
This was preventing the Nixpkgs channel from updating, since the
program indexer barfed on:

  error: anonymous function at /nix/store/wdnwbh3kmf68nhqqp0khcyxbdbp43vg5-nixos-14.12.626.b0d594c/nixos/nixpkgs/pkgs/top-level/node-packages.nix:1:1 called without required argument ‘neededNatives’, at /data/releases/nixos/unstable-small/.tmp-nixos-16.03pre72946.6bfe831-787/unpack/nixos-16.03pre72946.6bfe831/lib/customisation.nix:56:12

because Nixpkgs 16.03 was importing files from Nixpkgs 14.12.

Also added some half-assed checks to detect this issue in the future.